# ==================================== Course structure Tasks ===================
Design_Industry_Informed_Course:
  description: >
    First, research and identify the 5 most well-known companies in the field of {title}, specifically related to {topics}, and list their names. Second, using this company information, along with the provided domain ({domains}), categories ({categories}), learner's objectives ({objectives}), expectations ({expectations}), prerequisites ({prerequisites}), and desired level ({desired_level}), create a well-structured course outline for {title} focusing on {topics}. The structure should be divided into sections and subsections, and must facilitate progressive learning.
  expected_output: >
    A hierarchical course structure formatted in JSON. This structure will include section titles, a description for each section, and their associated subsections with their respective descriptions. The course design will leverage insights from the researched leading companies in the {title} and {topics} field. Do not number or enumerate the section titles. Never return an empty content in any levekl of the structure.
  agent: Comprehensive_Course_Architect

Finalize_Comprehensive_Course_Package:
  description: >
    Your comprehensive task is twofold:
    1.  **Project Design:** For each section outlined in the provided course structure (from the 'Design_Industry_Informed_Course' context), design one complex, multi-stage project. Each project must:
    -   Be based on the current course section's content and integrate knowledge from all previous sections.
    -   Solve a real-world problem relevant to {title} and {topics} in a practical, measurable way, leveraging company experiences/insights previously gathered.
    -   Require the learner to combine knowledge from the current session and prior sessions.
    -   Include at least 3 interdependent steps (e.g., research, implementation, testing, iteration).
    -   Have clear success criteria and a tangible output (e.g., prototype, report, algorithm).
    -   Challenge the learner to think critically and creatively.
    -   Ensure all projects have substantial content and are not empty.
    2.  **Course Compilation:** Once all projects are designed, assemble the complete course package for {title}. 
        This involves:
    -   Integrating the main course structure (sections, subsections, descriptions) from the 'Design_Industry_Informed_Course' context.
    -   Embedding the detailed project brief you designed for each section.
    -   Including a list of suggested quiz questions or key concepts to be quizzed for each section/session (you can generate these based on the section content).
    -   Ensuring consistent titles, language, and a smooth instructional flow throughout.
    -   Formatting the entire output as a clean, well-structured JSON document, ready for publication or API delivery.
    -   The JSON should include a course title and a brief introduction.
  expected_output: >
    A single, fully compiled course document in JSON format. This document must include:
    - "course_title": The title of the course.
    - "course_introduction": A brief introduction to the course.
    - "sections": An array of section objects. Each section object should contain:
      - "section_title": The title of the section (do not number).
      - "section_description": A description of the section.
      - "subsections": An array of subsection objects (if any), each with "subsection_title" and "subsection_description".
      - "project": An object detailing the hands-on project for that section, including:
        - "project_title": Clear, action-oriented name.
        - "project_description": Overview of the project.
        - "project_objective": Real-world problem it solves.
        - "project_prerequisites": List of concepts from current/prior sessions needed.
        - "project_steps": An array of detailed, sequential task descriptions (min. 3 steps).
        - "project_deliverable": Description of the tangible output format.
        - "project_evaluation_criteria": How the solution will be evaluated.
  agent: Lead_Curriculum_Finalizer
  context:
    - Design_Industry_Informed_Course