Company_researcher_task:
  description: >
    Search for the 5 most well-known companies in the field of {topic} and provide a list of their names.
  expected_output: >
    A list of company names in the {topic} industry, formatted in markdown.
  agent: Company_researcher


Course_planner_task:
    description: >
      Based on the {topic}, the learner's objectives {objective}, and prerequisites {prerequisites}, create a well-structured course outline. The structure should be divided into sections and subsections, and must facilitate progressive learning.
    expected_output: >
      A hierarchical course structure formatted in json, including section titles, the description of this section and their associated subsections et their description too. You will use the experiences of compagnies provided by the Company_researcher agent to create a personalized course structure You will use the experiences of compagnies provided by the Company_researcher agent in field of {topic} to create a personalized course structure.
    agent: Course_planner
    context:
      - Company_researcher_task


Quiz_builder_task: 
    description: >
      Create a quiz composed of at least 10 multiple-choice questions (MCQs) for each session. The questions should evaluate the learner's understanding of all subsections within the session.
    expected_output: >
      A set of MCQs question with at lease 4 options and the correct answer formatted in JSON or for each session. Each question should be clear, relevant, and aligned with the session's structure.
    agent: quiz_builder
    context: 
      - Course_planner_task


project_builder_task:
  description: >
    Design a hands-on project at the end of each section. The project should apply the concepts learned in the courent and previous sections, reinforce understanding, and promote creativity. It should include clear instructions, expected deliverables, and evaluation criteria.
  expected_output: >
    A project description document for each section, including objectives, steps, resources (if needed), and deliverables.
  agent: project_builder
  context:
    - Course_planner_task


Course_compiler_task:
  description: >
    Assemble a complete course package on {topic}, using the structure, quizzes, and project materials generated by the other agents. Format everything clearly and coherently, organizing the course into sections and subsections. Ensure consistency in titles, language, and instructional flow. Return a clean, well-structured document, preferably in json ready to be served via API exported. The document should be ready for publication or API delivery.
  expected_output: >
    A fully compiled course document including: 
    - Course title and introduction
    - Sections and subsections with their descriptions,
    - A list of quiz questions per session,
    - A hands-on project at the end of each section,
    - Proper formatting for publication or API delivery (json).
  agent: Course_compiler
  context:
    - Course_planner_task
    - Quiz_builder_task
    - project_builder_task