# ==================================== Course structure Tasks ===================

Company_researcher_task:
  description: >
    Search for the 5 most well-known companies in the field of {title} and provide a list of their names.
  expected_output: >
    A list of company names in the {title} industry, formatted in markdown.
  agent: Company_researcher

Course_planner_task:
    description: >
      Based on the {title} and {topics} concepts,the domain {domain}, the category {category} the learner's objectives {objectives}, the expectation {expectations} ,and prerequisites {prerequisites} and the disired level {disired_level}, create a well-structured course outline. The structure should be divided into sections and subsections, and must facilitate progressive learning.
    expected_output: >
      A hierarchical course structure formatted in json, including section titles, the description of this section and their associated subsections et their description too. You will use the experiences of compagnies provided by the Company_researcher agent to create a personalized course structure You will use the experiences of compagnies provided by the Company_researcher agent in field of {title} and {topics} concepts to create a personalized course structure. don't put nomber or enumerate the title section.
    agent: Course_planner
    context:
      - Company_researcher_task

project_builder_task:
  description: >
    Design a complex, multi-stage project in each section. each projet must based on the current course section and all previous sections. The project must:
    1. Solve a real-world problem in a practical, measurable way.
    2. Require the learner to combine knowledge from the current session and prior sessions.
    3. Include at least 3 interdependent steps (e.g., research, implementation, testing, iteration).
    4. Have clear success criteria and a tangible output (e.g., prototype, report, algorithm).
    5. Challenge the learner to think critically and creatively.
  expected_output: >
    A structured project brief with:
    - Title: Clear, action-oriented name.
    - description
    - Objective: Real-world problem it solves.
    - Prerequisites: List of concepts from current/prior sessions needed.
    - Steps: Detailed, sequential tasks (min. 3 steps).
    - Deliverable: Tangible output format (e.g., code, presentation, model).
    - evaluation criteria: How the solution will be evaluated.
  agent: project_builder
  context:
    - Course_planner_task

Course_compiler_task:
  description: >
    Assemble a complete course package on {title}, using the structure, quizzes, and project materials generated by the other agents. Format everything clearly and coherently, organizing the course into sections and subsections. Ensure consistency in titles, language, and instructional flow. Return a clean, well-structured document, preferably in json ready to be served via API exported. The document should be ready for publication or API delivery.
  expected_output: >
    A fully compiled course document including: 
    - Course title and introduction
    - Sections and subsections with their descriptions,
    - A list of quiz questions per session,
    - A hands-on project at the end of each section,
    - Proper formatting for publication or API delivery (json).
  agent: Course_compiler
  context:
    - Course_planner_task
    - project_builder_task